language: python
python:
    - "3.6"

before_install:
    - git config --global user.email "vaporize93@gmail.com"
    - git config --global user.name "harvey"

install: 
    - pip install -r requirements.txt -q

sctipt:
    - make publish

after_success: 
    - cd output
    - git add -A
    - git commit -m "Github Pages updated by Travis-CI."
    - git push https://${GH_TOKEN}@github.com/vaporize93/TIL.git gh-pages --quiet

branches:
    only:
        - master
